import Head from "next/head";
import { BsMoonFill, BsFillSunFill } from "react-icons/bs";
import { AiFillGithub } from "react-icons/ai";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { getWeatherData } from "@/lib/apiRequests";
import WeatherFeed from "@/components/WeatherFeed";
import Link from "next/link";

const index = function ({ weather }) {
  const [theme, setTheme] = useState("light");
  const toggleTheme = () => setTheme(theme === "light" ? "dark" : "light");

  const changeTheme = () => {
    toggleTheme();

    theme === "light"
      ? (document.body.classList.add("dark"),
        document.body.classList.remove("light"))
      : (document.body.classList.add("light"),
        document.body.classList.remove("dark"));
  };

  return (
    <>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.nav}>
        <div>
          <h3>Weather App</h3>
        </div>
        <div className={styles.sub__nav}>
          <div>
            {theme === "light" ? (
              <BsMoonFill onClick={changeTheme} className={styles.icon} />
            ) : (
              <BsFillSunFill onClick={changeTheme} className={styles.icon} />
            )}
          </div>
          <div>
            <Link href="https://github.com/trstefan">
              <AiFillGithub className={styles.icon_link} style="all:unset;" />
            </Link>
          </div>
        </div>
      </nav>
      <main className={styles.main}>
        <WeatherFeed weather={weather} />
      </main>
    </>
  );
};

export async function getServerSideProps() {
  const weather = await getWeatherData();
  return {
    props: {
      weather,
    },
  };
}

export default index;
